"""add back table OCCities

Revision ID: 41559db5787d
Revises: b9c56b146b8e
Create Date: 2021-04-04 13:22:11.468324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41559db5787d'
down_revision = 'b9c56b146b8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oc_cities',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('santa_ana', sa.Integer(), nullable=True),
    sa.Column('anaheim', sa.Integer(), nullable=True),
    sa.Column('garden_grove', sa.Integer(), nullable=True),
    sa.Column('huntington_beach', sa.Integer(), nullable=True),
    sa.Column('orange', sa.Integer(), nullable=True),
    sa.Column('fullerton', sa.Integer(), nullable=True),
    sa.Column('buena_park', sa.Integer(), nullable=True),
    sa.Column('irvine', sa.Integer(), nullable=True),
    sa.Column('costa_mesa', sa.Integer(), nullable=True),
    sa.Column('westminster', sa.Integer(), nullable=True),
    sa.Column('newport_beach', sa.Integer(), nullable=True),
    sa.Column('la_habra', sa.Integer(), nullable=True),
    sa.Column('tustin', sa.Integer(), nullable=True),
    sa.Column('placentia', sa.Integer(), nullable=True),
    sa.Column('stanton', sa.Integer(), nullable=True),
    sa.Column('mission_viejo', sa.Integer(), nullable=True),
    sa.Column('yorba_linda', sa.Integer(), nullable=True),
    sa.Column('lake_forest', sa.Integer(), nullable=True),
    sa.Column('cypress', sa.Integer(), nullable=True),
    sa.Column('fountain_valley', sa.Integer(), nullable=True),
    sa.Column('seal_beach', sa.Integer(), nullable=True),
    sa.Column('san_clemente', sa.Integer(), nullable=True),
    sa.Column('los_alamitos', sa.Integer(), nullable=True),
    sa.Column('brea', sa.Integer(), nullable=True),
    sa.Column('san_juan_capistrano', sa.Integer(), nullable=True),
    sa.Column('laguna_niguel', sa.Integer(), nullable=True),
    sa.Column('aliso_viejo', sa.Integer(), nullable=True),
    sa.Column('laguna_hills', sa.Integer(), nullable=True),
    sa.Column('laguna_beach', sa.Integer(), nullable=True),
    sa.Column('rancho_santa_margarita', sa.Integer(), nullable=True),
    sa.Column('dana_point', sa.Integer(), nullable=True),
    sa.Column('la_palma', sa.Integer(), nullable=True),
    sa.Column('midway_city', sa.Integer(), nullable=True),
    sa.Column('ladera_ranch', sa.Integer(), nullable=True),
    sa.Column('trabuco_canyon', sa.Integer(), nullable=True),
    sa.Column('villa_park', sa.Integer(), nullable=True),
    sa.Column('laguna_woods', sa.Integer(), nullable=True),
    sa.Column('rossmoor', sa.Integer(), nullable=True),
    sa.Column('rancho_mission_viejo', sa.Integer(), nullable=True),
    sa.Column('coto_de_caza', sa.Integer(), nullable=True),
    sa.Column('silverado', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('date')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('oc_cities')
    # ### end Alembic commands ###
