"""Initial migration.

Revision ID: b9c56b146b8e
Revises: 
Create Date: 2021-04-04 13:13:12.451917

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b9c56b146b8e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('oc_cities')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oc_cities',
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('santa_ana', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('anaheim', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('garden_grove', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('huntington_beach', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('orange', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('fullerton', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('buena_park', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('irvine', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('costa_mesa', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('westminster', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('newport_beach', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('la_habra', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('tustin', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('placentia', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('stanton', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('mission_viejo', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('yorba_linda', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('lake_forest', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('cypress', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('fountain_valley', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('seal_beach', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('san_clemente', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('los_alamitos', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('brea', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('san_juan_capistrano', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('laguna_niguel', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('aliso_viejo', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('laguna_hills', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('laguna_beach', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('rancho_santa_margarita', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('dana_point', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('la_palma', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('midway_city', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('ladera_ranch', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('trabuco_canyon', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('villa_park', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('laguna_woods', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('rossmoor', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('rancho_mission_viejo', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('coto_de_caza', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('silverado', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('date'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
